### PR TITLE
Update the image and video resources to avoid risks

### PR DESCRIPTION
**Pull request by NingW101**

### CODE REVIEW

**Comment by ibelem** [comment]
@NingW101 Have you moved Yang's materials back?

**Comment by NingW101** [comment]
> @NingW101 Have you moved Yang's materials back?

Moved these resources back in latest commit and renamed with the `-backup` suffix.

Btw, the new alternative resources are from `stockcake` - https://stockcake.com/info/about

**Comment by ibelem** [comment]
Please keep @gyagp 's resouces rather than rename them with "_backup". @NingW101

**Comment by NingW101** [comment]
> Please keep @gyagp 's resouces rather than rename them with "_backup". @NingW101

Done-

**Comment by ibelem** [comment]
LGTM, thanks!

**Pull request merged**
