### PR TITLE
Add Contributing section in README and thank Joshua Lochner for his contribution

### PR DESCRIPTION
**Pull request by gyagp**
We're so excited to get Joshua Lochner's permission to freely use images, videos and demos from Transformers.js project. Add a Contributing section in README to mention his contribution.

### CODE REVIEW

**Comment by gyagp** [comment]
@NingW101 @ibelem PTAL

**Comment by gyagp** [comment]
@xenova Thank you for your permission to use images, videos and demos from Transformers.js project. This is the PR to mention your contribution, and I hope you're fine with this :)

**Comment by ibelem** [comment]
LGTM, thanks @gyagp and @xenova !

**Comment by xenova** [comment]
Thanks so much! 🤗

**Pull request merged**
